#!/usr/bin/perl

#
# This is where everything exists. change this if you move to differnet dir.
#
$myPath = '/opt/itach'; 

chdir($myPath);

$ProgramName = 'itach_send_batch';

$Command = "$myPath/$ProgramName $myPath $ARGV[0] $ARGV[1] $ARGV[2] $ARGV[3] &";

#print $Command."\n";
#
# Runs with exec as not to lock up the user interface.
#
exec($Command);
